services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: stockstalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - stockstalk_pg:/var/lib/postgresql/data

volumes:
  stockstalk_pg:
